project/urls.py
from django.contrib import admin
from django.urls import path
from ayto.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', MasterList.as_view(), name='index'),
    path('results/', FinalResults.as_view(), name='final_results'),
    path('participant/<str:participant_slug>/', ParticipantView.as_view(), name='participant_index'),
    path('week/<int:week_number>/', WeeklyMatchup.as_view(), name='week_index'),
    path('week/<int:week_number>/overlaps/', WeekOverlaps.as_view(), name='week_overlaps'),
    path('potentialmatches/<str:participant1_slug>/<str:participant2_slug>/', PotentialMatchupDetail.as_view(), name='pm_detail'),
]

ayto/models.py
from django.db import models


class Participant(models.Model):
    name = models.CharField(max_length=100)
    full_name = models.CharField(max_length=100)
    picture = models.URLField(blank=True, null=True)
    url_slug = models.CharField(max_length=100, unique=True)

    @property
    def perfect_match(self):
        return self.potentialmatchup_qs.filter(perfect_match=True).first()

    @property
    def potentialmatchup_qs(self):
        return PotentialMatchup.objects.order_by('pk').filter(
            models.Q(participant1=self) |
            models.Q(participant2=self)
        )

    @property
    def potential_matchups(self):
        matchups = self.potentialmatchup_qs.all()
        formatted_matchups = []
        for matchup in matchups:
            formatted_matchup = {
                'eliminated': matchup.eliminated,
                'elimination_type': matchup.elimination_type,
                'potentialmatchup': matchup,
                'weeks_matched': matchup.matchup_set.all()
            }
            if matchup.participant1 == self:
                formatted_matchup['match'] = matchup.participant2
            else:
                formatted_matchup['match'] = matchup.participant1
            formatted_matchups.append(formatted_matchup)
        return formatted_matchups

    @property
    def eliminated_matchups(self):
        matchups = PotentialMatchup.objects.filter(
            models.Q(participant1=self) |
            models.Q(participant2=self)
        ).filter(
            models.Q(eliminated_via_blackout=True) |
            models.Q(eliminated_via_truthbooth=True) |
            models.Q(manually_eliminated=True)
        ).all()
        formatted_matchups = []
        for matchup in matchups:
            if matchup.participant1 == self:
                formatted_matchups.append(
                    {
                        'match': matchup.participant2,
                        'elimination_type': matchup.elimination_type
                    }
                )
            else:
                formatted_matchups.append(
                    {
                        'match': matchup.participant1,
                        'elimination_type': matchup.elimination_type
                    }
                )
        return formatted_matchups

    @classmethod
    def get(cls, participant):
        """ Returns an instance of Participant where given participant
            is either a full name or first name.

            If participant is already a participant object, just return it.
        """
        if isinstance(participant, cls):
            return participant
        elif isinstance(participant, str) and ' ' in participant:
            participant = Participant.objects.get(full_name=participant)
        elif isinstance(participant, str) and ' ' not in participant:
            participant = Participant.objects.get(name=participant)
        return participant

    def __str__(self):
        return self.full_name


class Week(models.Model):
    week_number = models.IntegerField()
    matches_count = models.IntegerField(default=0)
    locked = models.BooleanField(default=False)

    def __str__(self):
        return 'Week #{}'.format(self.week_number)

    @classmethod
    def get_set_weeks(cls):
        weeks = []
        for week in cls.objects.all().order_by('-week_number'):
            if week.matchup_set.count() > 0 or week.truthbooth_set.count() > 0:
                weeks.append(week)
        return weeks

    def get_available_participants(self):
        unavailable_participants = []
        # for tb in self.truthbooth_set.all():
        #     unavailable_participants.append(tb.matchup.participant1)
        #     unavailable_participants.append(tb.matchup.participant2)

        for pm in PotentialMatchup.objects.filter(perfect_match=True):
            unavailable_participants.append(pm.participant1)
            unavailable_participants.append(pm.participant2)

        for mu in self.matchup_set.all():
            unavailable_participants.append(mu.matchup.participant1)
            unavailable_participants.append(mu.matchup.participant2)


        available_participants = Participant.objects.exclude(
            pk__in=[p.pk for p in unavailable_participants]
        )
        return available_participants

    def save(self, *args, **kwargs):
        super(Week, self).save(*args, **kwargs)
        if self.matches_count == 0:
            for matchup in self.matchup_set.all():
                matchup.matchup.eliminated_via_blackout = True
                matchup.matchup.save()
        elif self.matches_count == self.matchup_set.count():
            for matchup in self.matchup_set.all():
                matchup.matchup.perfect_match = True
                matchup.matchup.save()
        else:
            for matchup in self.matchup_set.all():
                matchup.matchup.perfect_match = False
                matchup.matchup.eliminated_via_blackout = False
                matchup.matchup.save()

    def get_overlaps(self):
        overlaps = {}
        this_week_matchups = [ms.matchup for ms in self.matchup_set.all()]
        for week in Week.objects.exclude(pk=self.pk).all():
            diff_week_matchups = [ms.matchup for ms in week.matchup_set.all()]
            diff_overlaps = []
            for matchup in diff_week_matchups:
                if matchup in this_week_matchups:
                    diff_overlaps.append(matchup)
            if diff_overlaps:
                overlaps[week] = diff_overlaps
        return overlaps


    def get_overlaps_for_participant(self, participant):
        this_week_overlaps = self.get_overlaps
        overlaps_for_participant = {}
        for week, overlaps in this_week_overlaps.items():
            participant_in_matches = False
            for overlap in overlaps:
                if participant in [overlap.participant1, overlap.participant2]:
                    participant_in_matches = True
            if participant_in_matches:
                overlaps_for_participant[week] = overlaps


class PotentialMatchup(models.Model):
    participant1 = models.ForeignKey(
        Participant,
        related_name='potential_matchup_participant1',
        on_delete=models.CASCADE
    )
    participant2 = models.ForeignKey(
        Participant,
        related_name='potential_matchup_participant2',
        on_delete=models.CASCADE
    )
    speculative_match = models.BooleanField(default=False)
    perfect_match = models.BooleanField(default=False)
    perfect_match_via_truthbooth = models.BooleanField(default=False)
    manually_eliminated = models.BooleanField(default=False)
    eliminated_via_truthbooth = models.BooleanField(default=False)
    eliminated_via_blackout = models.BooleanField(default=False)

    class Meta:
        unique_together = ['participant1', 'participant2']

    @property
    def eliminated(self):
        if self.eliminated_via_truthbooth or self.eliminated_via_blackout:
            return True
        else:
            return self.manually_eliminated

    @property
    def elimination_type(self):
        if self.eliminated_via_truthbooth:
            return 'Eliminated Via Truthbooth'
        elif self.eliminated_via_blackout:
            return 'Eliminated Via Blackout'
        elif self.manually_eliminated:
            return 'Manual Elimination'
        elif self.perfect_match:
            if self.perfect_match_via_truthbooth:
                return 'Perfect Match: Truth Booth'
            return 'Final Match'
        elif self.speculative_match:
            return 'Speculative Match'
        return "can't be eliminated"

    @property
    def elimination_tag(self):
        if self.eliminated_via_truthbooth:
            return 'eliminated_via_truthbooth'
        elif self.eliminated_via_blackout:
            return 'eliminated_via_blackout'
        elif self.manually_eliminated:
            return 'manual_elimination'
        elif self.perfect_match:
            return 'perfect_match'
        elif self.speculative_match:
            return 'speculative_match'
        return 'not_eliminated'

    @property
    def related_matchups(self):
        return PotentialMatchup.objects.filter(
            models.Q(participant1__in=[self.participant1, self.participant2]) |
            models.Q(participant2__in=[self.participant1, self.participant2])
        ).exclude(pk=self.pk).all()

    @classmethod
    def get(cls, participant1, participant2):
        participant1 = Participant.get(participant1)
        participant2 = Participant.get(participant2)

        return cls.objects.filter(
            models.Q(participant1=participant1) |
            models.Q(participant2=participant1)
        ).filter(
            models.Q(participant1=participant2) |
            models.Q(participant2=participant2)
        ).first()

    @classmethod
    def get_all(cls, participant1, participant2):
        participant1 = Participant.get(participant1)
        participant2 = Participant.get(participant2)

        return cls.objects.filter(
            models.Q(
                models.Q(participant1=participant1) |
                models.Q(participant2=participant1)
            ) |
            models.Q(
                models.Q(participant1=participant2) |
                models.Q(participant2=participant2)
            )
        ).all()

    def set_perfect_match(self, match_type):
        for matchup in self.related_matchups:
            if match_type == 'truthbooth':
                matchup.eliminated_via_truthbooth = True
            else:
                matchup.manually_eliminated = True
            matchup.save()
        if match_type == 'truthbooth':
            self.perfect_match_via_truthbooth = True
        self.perfect_match = True
        self.save()


    def unset_perfect_match(self, match_type):
        if match_type == 'truthbooth':
            self.perfect_match_via_truthbooth = False
        else:
            self.perfect_match = False

ayto/templates/ayto/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="">
	<meta name="keywords" content="">
	<meta name="author" content="Bo Morin">
	<title>{% block page_title %}AYTO CALCULATOR{% endblock %}</title>
	<link rel="shortcut icon" href="" />
	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
	<link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
	<link href= 'https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/ui-lightness/jquery-ui.css' rel='stylesheet'> 
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js" > </script> 
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js" > </script>
	<script src="{% static 'vendors/bootstrap/js/bootstrap.min.js' %}"></script>
	<link href="{% static 'css/app.css' %}" rel="stylesheet">
</head>

<body>
<div class="wrapper">

    <!-- Sidebar -->
    <nav id="sidebar">
    		<a href="{% url 'index' %}"><strong>Match Up Master List</strong></a>
    		<a href="{% url 'final_results' %}"><strong>Final Results</strong></a>
			<ul class="list-unstyled components">
				<p>Participants</p>
				{% for participant in participants %}
				<li>
					<a href="{% url 'participant_index' participant_slug=participant.url_slug %}">
						{{participant.name}}
					</a>
				</li>
				{% endfor %}
			</ul>
			<ul class="list-unstyled components">
				<p>Weeks</p>
				{% for week in weeks %}
				<li>
					<a href="{% url 'week_index' week_number=week.week_number %}">
						Week #{{week.week_number}}
					</a>
				</li>
				{% endfor %}
			</ul>
		</div>
    </nav>
	<div id="content">
		{% block messages %}
			<div id="js-messages-row" class="row">
				<div id="js-messages-col" class="col">
				    {% for message in messages %}
				    <div class="alert alert-{% if message.level_tag == 'error'%}danger{% else %}{{message.level_tag}}{% endif %} alert-dismissible fade show" role="alert">
					 	<strong>{{message|safe}}</strong>
					 	<button type="button" class="close" data-dismiss="alert" aria-label="Close">
					 	<span aria-hidden="true">&times;</span>
					</div>
				    {% endfor %}
				</div>
			</div>
		{% endblock %}
		{% block page_content %}{% endblock %}
	</div>
</div>

ayto/templates/ayto/index.html
{% extends 'ayto/base.html' %}
{% load apptags %}

{% block page_content %}
	<div class="row">
		<div class="col"><h3>Match Ups</h3></div>
	</div>

	<div class="row">
		<div class="col">
			<div id="index-key"><span class="key">Color key:</span>
				<span class="key match-status_eliminated">Eliminated</span>
				<span class="key match-status_perfect-match">Perfect Match</span>
				<span class="key match-status_speculative-match">Speculative Match</span>
				<span class="key match-status_pending">Overlapped Match</span>
				<span class="key match-status_mismatch">Unknown Status</span>
			</div>
			<table class="table table-bordered">
				{% for week in weeks_rows %}
					<tr>
						<td>
							<div>Week&nbsp;{{week.week_number}}&nbsp;({{week.matches_count}}&nbsp;matches)</div>
							<div>Truth&nbsp;Booth</div>
							<div>
								{% for tb in week.truthbooth_set.all %}
									<strong>
									{{tb.matchup.participant1.name}} + {{tb.matchup.participant2.name}}</strong>
									<br />
									<strong>{{tb.match}}</strong>
								{% endfor %}
							</div>
							<div>
								<strong>Matches</strong>
								{% for match in week.matchup_set.all %}
								<div  class="match-status match-status_{% if match.matchup.eliminated %}eliminated{% elif match.matchup.perfect_match %}perfect-match{% elif match.matchup.speculative_match %}speculative-match{%else%}pending{% endif %}">
									<a href="{% url 'pm_detail' participant1_slug=match.matchup.participant1.url_slug participant2_slug=match.matchup.participant2.url_slug %}">{{match.matchup.participant1.name}} + {{match.matchup.participant2.name}}
									</a>
								</div>
								{% endfor %}
							</div>
						</td>
						{% for week_h in weeks_columns %}
						<td class="index-cell">
							{% with week|should_print_week:week_h as print_cell %}
							{% if print_cell %}
								{% if week_h.locked and week.locked > 0 %}
								<div class="index-label">
									[week{{week.week_number}} x week{{week_h.week_number}}]
								</div>
								{% else %}
									&nbsp;
								{% endif %}
								{% with week_h|get_overlaps:week as overlaps %}
									{% for overlap in overlaps %}									
									<div class="match-status match-status_{% if overlap.matchup.eliminated %}eliminated{% elif overlap.matchup.perfect_match %}perfect-match{% elif overlap.matchup.speculative_match %}speculative-match{%else%}pending{% endif %}">
										<a href="{% url 'pm_detail' participant1_slug=overlap.matchup.participant1.url_slug participant2_slug=overlap.matchup.participant2.url_slug %}">{{overlap.matchup.participant1.name}} + {{overlap.matchup.participant2.name}}
										</a>
									</div>
									{% endfor %}
								{% endwith %}

								{% with week_h|get_mismatches:week as mismatches %}
									{% for mismatch in mismatches %}									
									<div class="match-status match-status_{% if mismatch.matchup.eliminated %}eliminated{% elif mismatch.matchup.perfect_match %}perfect-match{% elif mismatch.matchup.speculative_match %}speculative-match{%else%}mismatch{% endif %}">
										<a href="{% url 'pm_detail' participant1_slug=mismatch.matchup.participant1.url_slug participant2_slug=mismatch.matchup.participant2.url_slug %}">{{mismatch.matchup.participant1.name}} + {{mismatch.matchup.participant2.name}}
										</a>
									</div>
									{% endfor %}
								{% endwith %}
							{% endif %}
							{% endwith %}
						</td>
						{% endfor %}
					</tr>
				{% endfor %}
			</table>
		</div>
	</div>
{% endblock %}

ayto/templates/ayto/matchup_detail.html
{% extends 'ayto/base.html' %}
{% load apptags %}
{% block page_content %}
	<div class="row">
		<div class="col">
				{% if pm.perfect_match %}
					<div class="alert alert-success">
				{% elif pm.speculative_match %}
					<div class="alert alert-primary">
				{% elif pm.eliminated %}
					<div class="alert alert-warning">
				{% else %}
					<div class="alert alert-light">
				{% endif %}
						<h2>Status: {{pm.elimination_type}}</h2>
				</div>
		</div>
	</div>
	</div>
	<div class="row">
		<div class="col-4">
			<h2>{{pm.participant1}}</h2>
			<img class="profile_img" src="{{pm.participant1.picture}}" />
		</div>
		<div class="col-3">
			{% if has_form_permission %}
			{% comment %}
			<div class="match-detail-button">
				<form method="POST">
					{% csrf_token %}
					{% if pm.perfect_match %}
						<input type="submit" class="btn btn-danger" name="unset-perfect-match" id="id_unset-perfect-match" value="Unset Perfect Match" />
					{% else %}
						<input type="submit" class="btn btn-success" name="set-perfect-match" id="id_set-perfect-match" value="Perfect match!" />
					{% endif %}
				</form>
			</div>
			{% endcomment %}
			<div class="match-detail-button">
				<form method="POST">
					{% csrf_token %}
					{% if pm.speculative_match %}
						<input type="submit" class="btn btn-danger" name="unset-speculative-match" id="id_unset-speculative-match" value="Unset Perfect Match" />
					{% else %}
						<input type="submit" class="btn btn-primary" name="set-speculative-match" id="id_set-speculative-match" value="Perfect Match?" />
					{% endif %}
				</form>
			</div>
			<div class="match-detail-button">
				<form method="POST">
					{% csrf_token %}
					{% if pm.manually_eliminated %}
						<input type="submit" class="btn btn-success" name="unset-manual-elimination" id="id_unset-manual-elimination" value="Unset Elimination" />
					{% else %}
						<input type="submit" class="btn btn-warning" name="set-manual-elimination" id="id_set-manual-elimination" value="Eliminate" />
					{% endif %}
				</form>
			</div>
			<div class="match-detail-button">
				<form method="POST">
					{% csrf_token %}
					{% if pm.perfect_match %}
						<input type="submit" class="btn btn-warning" name="unset-final-match" id="id_final-match" value="Unset Final Match" />
					{% else %}
						<input type="submit" class="btn btn-danger" name="set-final-match" id="id_set-final-match" value="Final Match!" />
					{% endif %}
				</form>
			</div>
			{% endif %}

		</div>
		<div class="col">
			<h2>{{pm.participant2}}</h2>
			<img class="profile_img" src="{{pm.participant2.picture}}" />
		</div>
	</div>
	<div class="row">
		<div class="col">
			<h4>Match ups</h4>
			<table class="table">
				{% for matchup in pm.matchup_set.all %}
					<tr>
						<th>Week #{{matchup.week.week_number}}</th>
						<td>
							<a href="{% url 'week_overlaps' week_number=matchup.week.week_number %}">
								total matches: {{matchup.week.matches_count}}
							</a>
						</td>
					</tr>
				{% endfor %}
			</table>
		</div>
	</div>
{% endblock %}

ayto/templates/ayto/participant.html
{% extends 'ayto/base.html' %}
{% load apptags %}

{% block page_content %}
	{% if participant.perfect_match %}
		<div class="row ">
			<div class="col">
				<div class="alert alert-success">
					<strong>PERFECT MATCH: </strong>{{participant.perfect_match}}
				</div>
			</div>
		</div>
	{% endif %}
	<div class="row">
		<div class="col-4">
			<h1>{{participant.full_name}}</h1>
			<img class="profile_img" src="{{participant.picture}}" />
		</div>
		<div class="col">
			<h3>Eliminations</h3>
			<table class="table">
				<tr>
					<th>Match</th>
					<th>Reason</th>
				</tr>
			{% for matchup in participant.eliminated_matchups %}
				<tr>
					<td>{{matchup.match.name}}</td>
					<td>{{matchup.elimination_type}}</td>
				</tr>
			{% endfor %}
			</table>
		</div>
	</div>
	<div class="row">
		<div class="col">
			<h3>Potential Matchups</h3>
			{{particpant.potential_matchups}}
			<table class="table">
				<tr>
					<th>Match</th>
					<th>Status</th>
					<th>Matched Weeks</th>
				</tr>
			{% for matchup in participant.potential_matchups %}
				<tr>
					<td><a href="{% url 'participant_index' participant_slug=matchup.match.url_slug %}">{{matchup.match.name}}</a></td>
					<td>{{matchup.elimination_type}}</td>
					<td>
						{% for matched_week in matchup.weeks_matched %}
							<strong>Week #{{matched_week.week.week_number}} ({{matched_week.week.matches_count}} total matches)</strong><br />
							{% with matched_week.week.get_overlaps|overlaps_for_participant:participant as weekly_overlaps %}
								{% if weekly_overlaps %}
									<strong>overlaps</strong>
									<table>
									{% for overlap_week, overlaps in weekly_overlaps.items %}
										<tr>
										{% for overlap in overlaps %}
											{% if forloop.first %}
												<td>Week #{{overlap_week.week_number}} </td>
											{% else %}
												<td></td>
											{% endif %}
											<td>
												<a href="{% url 'pm_detail' participant1_slug=overlap.participant1.url_slug participant2_slug=overlap.participant2.url_slug %}">
													{{overlap.participant1}} + {{overlap.participant2}}
												</a>
											</td>
										</tr>
										{% endfor %}
									{% endfor %}
									</table>
								{% endif %}
							{% endwith %}
							{% if not forloop.last %}<br />{% endif %}
						{% endfor %}
					</td>
				</tr>
			{% endfor %}
			</table>
		</div>
	</div>
{% endblock %}

ayto/templates/ayto/results.html
{% extends 'ayto/base.html' %}
{% load apptags %}
{% block page_content %}
	<div class="row">
		<div class="col">
			<table class="table">
				<tr>
					<th colspan="100%">Perfect Matches</th>
				</tr>
				{% for pm in perfect_matches %}
					<tr>
						<td>
							<div>{{pm.participant1.full_name}}</div>
							<div><img class="profile_img_results" src="{{pm.participant1.picture}}" /></div>
						</td>
						<td>
							<div class="final-result-type">
								{{pm.elimination_type}}
							</div>
						</td>
						<td>
							<div>{{pm.participant2.full_name}}</div>
							<div><img class="profile_img_results" src="{{pm.participant2.picture}}" /></div>
						</td>
						<td>
							<div class="final-result-type">
								{% if pm.speculative_match %}
									<div class="alert alert-success">You got it!</div>
								{% else %}
									<div class="alert alert-warning">You missed it!</div>
								{% endif %}
							</div>
						</td>
					</tr>
				{% endfor %}
			</table>
		</div>
	</div>
{% endblock %}

ayto/templates/ayto/week.html
{% extends 'ayto/base.html' %}

{% block page_content %}
	<div class="row">
		<div class="col">
			<h3>Week #{{week.week_number}}</h3>
		</div>
	</div>
	<div class="row">
		<div class="col">
			<h4>Matches</h4>
			<table class="table">
				<tr>
					<th>Participant 1</th>
					<th>Participant 2</th>
					<th></th>
				</tr>
				{% for match in week.matchup_set.all %}
						<tr>
							<td>{{match.matchup.participant1.name}}</td>
							<td>{{match.matchup.participant2.name}}</td>
							<td>
							{% if has_form_permission %}
								<form method="POST">
								{% csrf_token %}
									<input type="hidden" name="undo_match_pk" id="id_undo_match_pk" value="{{match.pk}}">
									<input name="undo-match" id="id_undo-match" type="submit" class="btn btn-warning" value="undo"/>
								</form>
							{% endif %}
							</td>
						</tr>
				{% endfor %}
				{% if available_participants and has_form_permission %}
					<form method="POST" action="">
						{% csrf_token %}
						<tr>
							<td>
								<select name="participant1" id="id_participant1" class="form-control">
									{% for participant in available_participants %}
										<option value="{{participant.pk}}">{{participant.name}}</option>
									{% endfor %}
								</select>
							</td>
							<td>
								<select name="participant2" id="id_participant2" class="form-control">
									{% for participant in available_participants %}
										<option value="{{participant.pk}}">{{participant.name}}</option>
									{% endfor %}
								</select>
							</td>
							<td>
								<input class="form-control btn btn-primary" type="submit" name="lock-match" id="lock-match" value="Lock" />
							</td>
						</tr>
					</form>
				{% endif %}
			</table>
			<table class="table">
				{% if has_form_permission %}
				<form method="POST" action="">
					{% csrf_token %}
					<tr>
						<th><label for="id_num_matches">Number of matches:</label></th>
						<td><input type="text" name="num_matches" id="id_num_matches" class="form-control" /></td>
						<td><input class="form-control btn btn-primary" type="submit" name="lock-num-matches" id="lock-num-matches" value="Lock" /></td>
					</tr>
				</form>
				{% endif %}
			</table>
		</div>
		<div class="col">
			<h4>Truth Booth</h4>
			<table class="table">
				<tr>
					<th>Participant 1</th>
					<th>Participant 2</th>
					<th colspan="2">Perfect Match</th>
				</tr>
				{% for tb in week.truthbooth_set.all %}
					<tr>
						<td>{{tb.matchup.participant1.name}}</td>
						<td>{{tb.matchup.participant2.name}}</td>
						<td>{{tb.match}}</td>
						<td>
							{% if request.user.is_superuser %}
							<form method="POST">
							{% csrf_token %}
								<input type="hidden" name="undo_truthbooth_pk" id="id_undo_truthbooth_pk" value="{{tb.pk}}">
								<input name="undo-truthbooth" id="id_undo-truthbooth" type="submit" class="btn btn-warning" value="undo"/>
							</form>
							{% endif %}
						</td>
					</tr>
				{% endfor %}
				{% if available_participants and request.user.is_superuser %}
					<form method="POST" action="">
						{% csrf_token %}
						<tr>
							<td>
								<select name="participant1" id="id_participant1" class="form-control">
									{% for participant in available_participants %}
										<option value="{{participant.pk}}">{{participant.name}}</option>
									{% endfor %}
								</select>
							</td>
							<td>
								<select name="participant2" id="id_participant2" class="form-control">
									{% for participant in available_participants %}
										<option value="{{participant.pk}}">{{participant.name}}</option>
									{% endfor %}
								</select>
							</td>
							<td>
								<input class="form-control" type="checkbox" name="perfect_match" id="id_perfect_match" value="Y" />
							</td>
							<td>
								<input class="form-control btn btn-primary" type="submit" name="lock-truthbooth" id="lock-truthbooth" value="Lock" />
							</td>
						</tr>
					</form>
				{% endif %}
			</table>
			{% if week.matches_count %}
				<h1>{{week.matches_count}} MATCH{% if week.matches_count > 1 %}ES{% endif %}</h1>
			{% else %}
				<h1>0 MATCHES</h1>
			{% endif %}
		</div>
	</div>

{% endblock %}